@echo off
del /Q clean.bat del.bat cleanup.bat cleanup.js cleanup.vbs run-cleanup.bat run.ps1 remove-artifacts.ps1
del /Q AUDIT_FIX_TODO.md AUDIT_ORCHESTRATION_PLAN.md CODE_QUALITY_AUDIT.md DASHBOARD_ARCHITECT_REVIEW.md DASHBOARD_TABLE DASHBOARD_TABLE_FORMAT.md DOCKER_BLOCKERS_REPORT.md ENHANCED_AUDIT_REPORT.md EXTERNAL_QUALITY_AUDIT.md FINAL_AUDIT_SUMMARY.md PAGE_CLASSIFICATION.md PRODUCTION_ANALYSIS.md SECURITY_AUDIT_API.md SECURITY_AUDIT_CONTRACTS.md TODO.md D fix-push.bat
del x.bat
