/**
 * REMEDIATED: This service has been upgraded to use a production-grade database (PostgreSQL via Prisma)
 * instead of a local JSON file. This ensures data persistence and scalability in a clustered environment.
 * The corresponding 'Deployment' model must be added to the 'schema.prisma' file.
 */
const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

class DeploymentPersistenceService {
    constructor() {
        // The service is now stateless, relying on the Prisma client.
        console.log('[DEPLOYMENT-PERSISTENCE] Upgraded to use PostgreSQL via Prisma.');
    }

    async getAll() {
        return await prisma.deployment.findMany({
            orderBy: { createdAt: 'desc' }
        });
    }

    async getById(id) {
        return await prisma.deployment.findUnique({
            where: { id }
        });
    }

    async create(deploymentData) {
        // The ID is now auto-generated by the database.
        const { id, ...data } = deploymentData;
        return await prisma.deployment.create({
            data: data
        });
    }

    async update(id, updates) {
        const existing = await this.getById(id);
        if (!existing) return null;

        return await prisma.deployment.update({
            where: { id },
            data: updates
        });
    }
}

module.exports = new DeploymentPersistenceService();