/**
 * REMEDIATED: This service has been upgraded to use a production-grade database (PostgreSQL via Prisma)
 * instead of a local JSON file. This ensures data persistence and scalability in a clustered environment.
 * The corresponding 'Deployment' model must be added to the 'schema.prisma' file.
 * 
 * Note: This service now gracefully handles database connection errors by returning empty arrays.
 */
const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

class DeploymentPersistenceService {
    constructor() {
        // The service is now stateless, relying on the Prisma client.
        console.log('[DEPLOYMENT-PERSISTENCE] Service initialized.');
    }

    async getAll() {
        try {
            return await prisma.deployment.findMany({
                orderBy: { createdAt: 'desc' }
            });
        } catch (error) {
            console.error('[DEPLOYMENT-PERSISTENCE] Error fetching deployments:', error.message);
            return []; // Return empty array on error
        }
    }

    async getById(id) {
        try {
            return await prisma.deployment.findUnique({
                where: { id }
            });
        } catch (error) {
            console.error('[DEPLOYMENT-PERSISTENCE] Error fetching deployment:', error.message);
            return null;
        }
    }

    async create(deploymentData) {
        try {
            // The ID is now auto-generated by the database.
            const { id, ...data } = deploymentData;
            return await prisma.deployment.create({
                data: data
            });
        } catch (error) {
            console.error('[DEPLOYMENT-PERSISTENCE] Error creating deployment:', error.message);
            return null;
        }
    }

    async update(id, updates) {
        try {
            const existing = await this.getById(id);
            if (!existing) return null;

            return await prisma.deployment.update({
                where: { id },
                data: updates
            });
        } catch (error) {
            console.error('[DEPLOYMENT-PERSISTENCE] Error updating deployment:', error.message);
            return null;
        }
    }
}

module.exports = new DeploymentPersistenceService();